version: "2"
linters:
  settings:
    exhaustruct:
      exclude:
        - '.+/cobra\.Command$'
        - '.+/*\Decorator$'
    errcheck:
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)

  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - exhaustruct
