services:
  proxy:
    image: traefik:v3
    command:
      # Enable Docker provider
      # - "--providers.docker=true"
      # - "--providers.docker.exposedbydefault=false"
      # API and dashboard (optional, for debugging)
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      # Entry point configuration
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:4000"
    ports:
      - "4000:4000"
      - "8081:8080"
    volumes:
      - ./traefik/local/dynamic:/etc/traefik/dynamic
