services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    container_name: database
    platform: linux/arm64
    ports:
      - "5432:5432"
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    depends_on:
      - db
    image: playground:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env

  loki:
    image: grafana/loki:2.2.1
    command: -config.file=/etc/loki/loki-config.yaml
    ports:
      - 3100:3100
    volumes:
      - ./loki:/etc/loki
      - ./loki-data:/loki-data

  vector:
    image: timberio/vector:latest-alpine
    volumes:
      - ./vector:/etc/vector
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["-c", "/etc/vector/vector.yaml"]
    ports:
      - "8686:8686"
    container_name: vector
    depends_on:
      - loki
      - app

volumes:
  postgres-data:
