FROM kartoza/postgis:16-3.4

# Install pgvector extension
RUN apt-get update && \
    apt-get install -y postgresql-server-dev-17 git build-essential && \
    git clone --branch v0.8.0 https://github.com/pgvector/pgvector.git /pgvector && \
    cd /pgvector && make && make install && \
    rm -rf /pgvector && \
    apt-get remove -y build-essential git && apt-get autoremove -y && apt-get clean
