// Code generated by BobGen psql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import models "github.com/tkahng/authgo/internal/db/models"

type (
	NotificationType          = models.NotificationType
	ProviderTypes             = models.ProviderTypes
	Providers                 = models.Providers
	StripePricingPlanInterval = models.StripePricingPlanInterval
	StripePricingType         = models.StripePricingType
	StripeSubscriptionStatus  = models.StripeSubscriptionStatus
	TaskProjectStatus         = models.TaskProjectStatus
	TaskStatus                = models.TaskStatus
	TokenTypes                = models.TokenTypes
)

func allNotificationType() []NotificationType {
	return models.AllNotificationType()
}

func allProviderTypes() []ProviderTypes {
	return models.AllProviderTypes()
}

func allProviders() []Providers {
	return models.AllProviders()
}

func allStripePricingPlanInterval() []StripePricingPlanInterval {
	return models.AllStripePricingPlanInterval()
}

func allStripePricingType() []StripePricingType {
	return models.AllStripePricingType()
}

func allStripeSubscriptionStatus() []StripeSubscriptionStatus {
	return models.AllStripeSubscriptionStatus()
}

func allTaskProjectStatus() []TaskProjectStatus {
	return models.AllTaskProjectStatus()
}

func allTaskStatus() []TaskStatus {
	return models.AllTaskStatus()
}

func allTokenTypes() []TokenTypes {
	return models.AllTokenTypes()
}
