http:
  routers:
    backend:
      rule: "PathPrefix(`/api`)"
      service: backend
      entryPoints:
        - web
      priority: 100 # Add this

    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend
      entryPoints:
        - web
      priority: 1 # Add this

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8080"

    frontend:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5173"
