export const RouteMap = {
  ROCK_PAPER_SCISSORS: "/rock-paper-scissors",
  ACCOUNT_ROCK_PAPER_SCISSORS: "/account/rock-paper-scissors",
  VERIFY_EMAIL: "/verify-email",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/password-reset",
  FEATURES: "/features",
  PRICING: "/pricing",
  ABOUT: "/about",
  SAY_HELLO: "/say-hello",
  CONTACT: "/contact",
  HOME: "/",
  LANDING_HOME: "/home",
  ACCOUNT_DASHBOARD: "/account/dashboard",
  ACCOUNT_OVERVIEW_TEAMS: "/account/teams",
  ACCOUNT_OVERVIEW_TEAMS_INVITATION: "/account/teams-invitations",
  SETTINGS: "/account/settings",
  BILLING_SETTINGS: "/account/settings/billing",
  POINTS_SETTINGS: "/account/settings/points",

  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SIGNOUT: "/signout",

  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_SUBSCRIPTIONS: "/admin/subscriptions",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ROLES: "/admin/roles",
  ADMIN_PERMISSIONS: "/admin/permissions",
  ADMIN_JOBS: "/admin/jobs",
  ADMIN_PLAN_FEATURES: "/admin/plan-features",
  ADMIN_AI_USAGE: "/admin/ai-usage",
  PROTECTED: "/protected",
  PROTECTED_BASIC: "/protected/basic",
  PROTECTED_PRO: "/protected/pro",
  PROTECTED_ADVANCED: "/protected/advanced",
  DASHBOARD_KANBAN: "/kanban",
  DASHBOARD: "/dashboard",

  TASK_PROJECTS: "/projects",
  TASKS_HOME: "/tasks",
  PAYMENT: "/payment",

  TEAM_LIST: "/teams",
  TEAM_LIST_SLUG: "/teams/:teamSlug",

  ACCOUNT_FRIENDS: "/account/friends",
};
