export enum RouteMap {
  HASH = "#",
  API_STRIPE_PAYMENT = "/api/stripe/payment",
  API_STRIPE_SUBSCRIPTION = "/api/stripe/subscribe",
  FORGOT_PASSWORD = "/forgot-password",
  RESET_PASSWORD = "/reset-password",
  FEATURES = "/features",
  PRICING = "/pricing",
  ABOUT = "/about",
  CONTACT = "/contact",
  HOME = "/",
  LANDING_HOME = "/home",
  DASHBOARD_SUBSCRIPTIONS = "/dashboard/subscriptions",
  DASHBOARD_CHAT_HISTORY = "/dashboard/chat/history",
  DASHBOARD_CHAT_HOME = "/dashboard/chat",
  DASHBOARD_CHAT_PAGE = "/dashboard/chat/:chatId",
  DASHBOARD_CHAT_PARAMS = ":chatId",
  DASHBOARD_HOME = "/dashboard",
  ACCOUNT_SETTINGS = "/settings/account",
  BILLING_SETTINGS = "/settings/billing",

  SIGNIN = "/signin",
  SIGNUP = "/signup",
  SIGNOUT = "/signout",
  AUTH_PROVIDER = "/auth/:provider",
  PROVIDER_PARAMS = ":provider",
  AUTH_CALLBACK = "/auth/callback",
  ROLE_EDIT = "/dashboard/roles/:roleId",

  ADMIN_DASHBOARD_HOME = "/admin/dashboard",
  ADMIN_DASHBOARD_USERS = "/admin/dashboard/users",
  ADMIN_DASHBOARD_ROLES = "/admin/dashboard/roles",
  ADMIN_DASHBOARD_PERMISSIONS = "/admin/dashboard/permissions",

  PROTECTED_BASIC = "/dashboard/protected/basic",
  PROTECTED_PRO = " /dashboard/protected/pro",
  PROTECTED_ADVANCED = "/dashboard/protected/advanced",
}
