export const RouteMap = {
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/password-reset",
  FEATURES: "/features",
  PRICING: "/pricing",
  ABOUT: "/about",
  CONTACT: "/contact",
  HOME: "/",
  LANDING_HOME: "/home",
  DASHBOARD: "/dashboard",
  SETTINGS: "/settings",
  BILLING_SETTINGS: "/settings/billing",

  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SIGNOUT: "/signout",

  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_SUBSCRIPTIONS: "/admin/subscriptions",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ROLES: "/admin/roles",
  ADMIN_PERMISSIONS: "/admin/permissions",

  PROTECTED: "/protected",
  PROTECTED_BASIC: "/protected/basic",
  PROTECTED_PRO: "/protected/pro",
  PROTECTED_ADVANCED: "/protected/advanced",
  DASHBOARD_KANBAN: "/kanban",
  TASK_PROJECTS: "/projects",
  TASKS_HOME: "/tasks",
  PAYMENT: "/payment",

  TEAM_LIST: "/teams",
};
