// Code generated by BobGen psql v0.31.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_test

import (
	"context"
	"database/sql"
	"errors"
	// "os"
	"testing"

	_ "github.com/jackc/pgx/v5/stdlib"
	"github.com/stephenafamo/bob"
	models "github.com/tkahng/authgo/internal/db/models"
	factory "github.com/tkahng/authgo/internal/db/models/factory"
)

func TestAppParamUniqueConstraintErrors(t *testing.T) {
	db, err := sql.Open("pgx", "postgres://postgres:postgres@localhost:5432/authgo_test?sslmode=disable")
	if err != nil {
		t.Fatal("Error connecting to database")
	}
	tests := []struct {
		name        string
		expectedErr *models.UniqueConstraintError
		applyFn     func(tpl *factory.AppParamTemplate, obj *models.AppParam)
	}{
		{
			name:        "ErrUniqueAppParamsPkey",
			expectedErr: models.AppParamErrors.ErrUniqueAppParamsPkey,
			applyFn: func(tpl *factory.AppParamTemplate, obj *models.AppParam) {
				tpl.Apply(
					factory.AppParamMods.RandomizeAllColumns(nil),
					factory.AppParamMods.ID(obj.ID),
				)
			},
		},

		{
			name:        "ErrUniqueAppParamsNameKey",
			expectedErr: models.AppParamErrors.ErrUniqueAppParamsNameKey,
			applyFn: func(tpl *factory.AppParamTemplate, obj *models.AppParam) {
				tpl.Apply(
					factory.AppParamMods.RandomizeAllColumns(nil),
					factory.AppParamMods.Name(obj.Name),
				)
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx := context.Background()
			tx, err := db.Begin()
			if err != nil {
				t.Fatal("Couldn't start database transaction")
			}
			exec := bob.New(tx)
			f := factory.New()
			tpl := f.NewAppParam(factory.AppParamMods.RandomizeAllColumns(nil))
			obj, err := tpl.Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}
			tt.applyFn(tpl, obj)
			_, err = models.AppParams.Insert(tpl.BuildSetter()).One(ctx, exec)
			if !errors.Is(models.ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !models.ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if err = tx.Rollback(); err != nil {
				t.Fatal("Couldn't rollback database transaction")
			}
		})
	}
}
