// Code generated by BobGen psql v0.34.2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// UserSession is an object representing the database table.
type UserSession struct {
	ID           uuid.UUID `db:"id,pk" json:"id"`
	UserID       uuid.UUID `db:"user_id" json:"user_id"`
	Expires      time.Time `db:"expires" json:"expires"`
	SessionToken string    `db:"session_token" json:"session_token"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`

	R userSessionR `db:"-" json:"-"`
}

// UserSessionSlice is an alias for a slice of pointers to UserSession.
// This should almost always be used instead of []*UserSession.
type UserSessionSlice []*UserSession

// UserSessions contains methods to work with the user_sessions table
var UserSessions = psql.NewTablex[*UserSession, UserSessionSlice, *UserSessionSetter]("", "user_sessions")

// UserSessionsQuery is a query on the user_sessions table
type UserSessionsQuery = *psql.ViewQuery[*UserSession, UserSessionSlice]

// userSessionR is where relationships are stored.
type userSessionR struct {
	User *User `json:"User"` // user_sessions.user_sessions_user_id_fkey
}

type userSessionColumnNames struct {
	ID           string
	UserID       string
	Expires      string
	SessionToken string
	CreatedAt    string
	UpdatedAt    string
}

var UserSessionColumns = buildUserSessionColumns("user_sessions")

type userSessionColumns struct {
	tableAlias   string
	ID           psql.Expression
	UserID       psql.Expression
	Expires      psql.Expression
	SessionToken psql.Expression
	CreatedAt    psql.Expression
	UpdatedAt    psql.Expression
}

func (c userSessionColumns) Alias() string {
	return c.tableAlias
}

func (userSessionColumns) AliasedAs(alias string) userSessionColumns {
	return buildUserSessionColumns(alias)
}

func buildUserSessionColumns(alias string) userSessionColumns {
	return userSessionColumns{
		tableAlias:   alias,
		ID:           psql.Quote(alias, "id"),
		UserID:       psql.Quote(alias, "user_id"),
		Expires:      psql.Quote(alias, "expires"),
		SessionToken: psql.Quote(alias, "session_token"),
		CreatedAt:    psql.Quote(alias, "created_at"),
		UpdatedAt:    psql.Quote(alias, "updated_at"),
	}
}

type userSessionWhere[Q psql.Filterable] struct {
	ID           psql.WhereMod[Q, uuid.UUID]
	UserID       psql.WhereMod[Q, uuid.UUID]
	Expires      psql.WhereMod[Q, time.Time]
	SessionToken psql.WhereMod[Q, string]
	CreatedAt    psql.WhereMod[Q, time.Time]
	UpdatedAt    psql.WhereMod[Q, time.Time]
}

func (userSessionWhere[Q]) AliasedAs(alias string) userSessionWhere[Q] {
	return buildUserSessionWhere[Q](buildUserSessionColumns(alias))
}

func buildUserSessionWhere[Q psql.Filterable](cols userSessionColumns) userSessionWhere[Q] {
	return userSessionWhere[Q]{
		ID:           psql.Where[Q, uuid.UUID](cols.ID),
		UserID:       psql.Where[Q, uuid.UUID](cols.UserID),
		Expires:      psql.Where[Q, time.Time](cols.Expires),
		SessionToken: psql.Where[Q, string](cols.SessionToken),
		CreatedAt:    psql.Where[Q, time.Time](cols.CreatedAt),
		UpdatedAt:    psql.Where[Q, time.Time](cols.UpdatedAt),
	}
}

var UserSessionErrors = &userSessionErrors{
	ErrUniqueUserSessionsPkey: &UniqueConstraintError{s: "user_sessions_pkey"},

	ErrUniqueUserSessionsSessionTokenKey: &UniqueConstraintError{s: "user_sessions_session_token_key"},
}

type userSessionErrors struct {
	ErrUniqueUserSessionsPkey *UniqueConstraintError

	ErrUniqueUserSessionsSessionTokenKey *UniqueConstraintError
}

// UserSessionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type UserSessionSetter struct {
	ID           omit.Val[uuid.UUID] `db:"id,pk" json:"id"`
	UserID       omit.Val[uuid.UUID] `db:"user_id" json:"user_id"`
	Expires      omit.Val[time.Time] `db:"expires" json:"expires"`
	SessionToken omit.Val[string]    `db:"session_token" json:"session_token"`
	CreatedAt    omit.Val[time.Time] `db:"created_at" json:"created_at"`
	UpdatedAt    omit.Val[time.Time] `db:"updated_at" json:"updated_at"`
}

func (s UserSessionSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if !s.ID.IsUnset() {
		vals = append(vals, "id")
	}

	if !s.UserID.IsUnset() {
		vals = append(vals, "user_id")
	}

	if !s.Expires.IsUnset() {
		vals = append(vals, "expires")
	}

	if !s.SessionToken.IsUnset() {
		vals = append(vals, "session_token")
	}

	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}

	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}

	return vals
}

func (s UserSessionSetter) Overwrite(t *UserSession) {
	if !s.ID.IsUnset() {
		t.ID, _ = s.ID.Get()
	}
	if !s.UserID.IsUnset() {
		t.UserID, _ = s.UserID.Get()
	}
	if !s.Expires.IsUnset() {
		t.Expires, _ = s.Expires.Get()
	}
	if !s.SessionToken.IsUnset() {
		t.SessionToken, _ = s.SessionToken.Get()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt, _ = s.CreatedAt.Get()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt, _ = s.UpdatedAt.Get()
	}
}

func (s *UserSessionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return UserSessions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID.IsUnset() {
			vals[0] = psql.Raw("DEFAULT")
		} else {
			vals[0] = psql.Arg(s.ID)
		}

		if s.UserID.IsUnset() {
			vals[1] = psql.Raw("DEFAULT")
		} else {
			vals[1] = psql.Arg(s.UserID)
		}

		if s.Expires.IsUnset() {
			vals[2] = psql.Raw("DEFAULT")
		} else {
			vals[2] = psql.Arg(s.Expires)
		}

		if s.SessionToken.IsUnset() {
			vals[3] = psql.Raw("DEFAULT")
		} else {
			vals[3] = psql.Arg(s.SessionToken)
		}

		if s.CreatedAt.IsUnset() {
			vals[4] = psql.Raw("DEFAULT")
		} else {
			vals[4] = psql.Arg(s.CreatedAt)
		}

		if s.UpdatedAt.IsUnset() {
			vals[5] = psql.Raw("DEFAULT")
		} else {
			vals[5] = psql.Arg(s.UpdatedAt)
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s UserSessionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s UserSessionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if !s.ID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if !s.UserID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "user_id")...),
			psql.Arg(s.UserID),
		}})
	}

	if !s.Expires.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "expires")...),
			psql.Arg(s.Expires),
		}})
	}

	if !s.SessionToken.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "session_token")...),
			psql.Arg(s.SessionToken),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindUserSession retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindUserSession(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*UserSession, error) {
	if len(cols) == 0 {
		return UserSessions.Query(
			SelectWhere.UserSessions.ID.EQ(IDPK),
		).One(ctx, exec)
	}

	return UserSessions.Query(
		SelectWhere.UserSessions.ID.EQ(IDPK),
		sm.Columns(UserSessions.Columns().Only(cols...)),
	).One(ctx, exec)
}

// UserSessionExists checks the presence of a single record by primary key
func UserSessionExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return UserSessions.Query(
		SelectWhere.UserSessions.ID.EQ(IDPK),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after UserSession is retrieved from the database
func (o *UserSession) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserSessions.AfterSelectHooks.RunHooks(ctx, exec, UserSessionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = UserSessions.AfterInsertHooks.RunHooks(ctx, exec, UserSessionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = UserSessions.AfterUpdateHooks.RunHooks(ctx, exec, UserSessionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = UserSessions.AfterDeleteHooks.RunHooks(ctx, exec, UserSessionSlice{o})
	}

	return err
}

// PrimaryKeyVals returns the primary key values of the UserSession
func (o *UserSession) PrimaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *UserSession) pkEQ() dialect.Expression {
	return psql.Quote("user_sessions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		return o.PrimaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the UserSession
func (o *UserSession) Update(ctx context.Context, exec bob.Executor, s *UserSessionSetter) error {
	v, err := UserSessions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single UserSession record with an executor
func (o *UserSession) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := UserSessions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the UserSession using the executor
func (o *UserSession) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := UserSessions.Query(
		SelectWhere.UserSessions.ID.EQ(o.ID),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after UserSessionSlice is retrieved from the database
func (o UserSessionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = UserSessions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = UserSessions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = UserSessions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = UserSessions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o UserSessionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("user_sessions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.Writer, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.PrimaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o UserSessionSlice) copyMatchingRows(from ...*UserSession) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o UserSessionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserSessions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserSession:
				o.copyMatchingRows(retrieved)
			case []*UserSession:
				o.copyMatchingRows(retrieved...)
			case UserSessionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserSession or a slice of UserSession
				// then run the AfterUpdateHooks on the slice
				_, err = UserSessions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o UserSessionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return UserSessions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *UserSession:
				o.copyMatchingRows(retrieved)
			case []*UserSession:
				o.copyMatchingRows(retrieved...)
			case UserSessionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a UserSession or a slice of UserSession
				// then run the AfterDeleteHooks on the slice
				_, err = UserSessions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o UserSessionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals UserSessionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserSessions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o UserSessionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := UserSessions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o UserSessionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := UserSessions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type userSessionJoins[Q dialect.Joinable] struct {
	typ  string
	User func(context.Context) modAs[Q, userColumns]
}

func (j userSessionJoins[Q]) aliasedAs(alias string) userSessionJoins[Q] {
	return buildUserSessionJoins[Q](buildUserSessionColumns(alias), j.typ)
}

func buildUserSessionJoins[Q dialect.Joinable](cols userSessionColumns, typ string) userSessionJoins[Q] {
	return userSessionJoins[Q]{
		typ:  typ,
		User: userSessionsJoinUser[Q](cols, typ),
	}
}

func userSessionsJoinUser[Q dialect.Joinable](from userSessionColumns, typ string) func(context.Context) modAs[Q, userColumns] {
	return func(ctx context.Context) modAs[Q, userColumns] {
		return modAs[Q, userColumns]{
			c: UserColumns,
			f: func(to userColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Users.Name().As(to.Alias())).On(
						to.ID.EQ(from.UserID),
					))
				}

				return mods
			},
		}
	}
}

// User starts a query for related objects on users
func (o *UserSession) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	return Users.Query(append(mods,
		sm.Where(UserColumns.ID.EQ(psql.Arg(o.UserID))),
	)...)
}

func (os UserSessionSlice) User(mods ...bob.Mod[*dialect.SelectQuery]) UsersQuery {
	PKArgs := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgs[i] = psql.ArgGroup(o.UserID)
	}

	return Users.Query(append(mods,
		sm.Where(psql.Group(UserColumns.ID).In(PKArgs...)),
	)...)
}

func (o *UserSession) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "User":
		rel, ok := retrieved.(*User)
		if !ok {
			return fmt.Errorf("userSession cannot load %T as %q", retrieved, name)
		}

		o.R.User = rel

		if rel != nil {
			rel.R.UserSessions = UserSessionSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("userSession has no relationship %q", name)
	}
}

func PreloadUserSessionUser(opts ...psql.PreloadOption) psql.Preloader {
	return psql.Preload[*User, UserSlice](orm.Relationship{
		Name: "User",
		Sides: []orm.RelSide{
			{
				From: TableNames.UserSessions,
				To:   TableNames.Users,
				FromColumns: []string{
					ColumnNames.UserSessions.UserID,
				},
				ToColumns: []string{
					ColumnNames.Users.ID,
				},
			},
		},
	}, Users.Columns().Names(), opts...)
}

func ThenLoadUserSessionUser(queryMods ...bob.Mod[*dialect.SelectQuery]) psql.Loader {
	return psql.Loader(func(ctx context.Context, exec bob.Executor, retrieved any) error {
		loader, isLoader := retrieved.(interface {
			LoadUserSessionUser(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
		})
		if !isLoader {
			return fmt.Errorf("object %T cannot load UserSessionUser", retrieved)
		}

		err := loader.LoadUserSessionUser(ctx, exec, queryMods...)

		// Don't cause an issue due to missing relationships
		if errors.Is(err, sql.ErrNoRows) {
			return nil
		}

		return err
	})
}

// LoadUserSessionUser loads the userSession's User into the .R struct
func (o *UserSession) LoadUserSessionUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.User = nil

	related, err := o.User(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.UserSessions = UserSessionSlice{o}

	o.R.User = related
	return nil
}

// LoadUserSessionUser loads the userSession's User into the .R struct
func (os UserSessionSlice) LoadUserSessionUser(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	users, err := os.User(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		for _, rel := range users {
			if o.UserID != rel.ID {
				continue
			}

			rel.R.UserSessions = append(rel.R.UserSessions, o)

			o.R.User = rel
			break
		}
	}

	return nil
}

func attachUserSessionUser0(ctx context.Context, exec bob.Executor, count int, userSession0 *UserSession, user1 *User) (*UserSession, error) {
	setter := &UserSessionSetter{
		UserID: omit.From(user1.ID),
	}

	err := userSession0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachUserSessionUser0: %w", err)
	}

	return userSession0, nil
}

func (userSession0 *UserSession) InsertUser(ctx context.Context, exec bob.Executor, related *UserSetter) error {
	user1, err := Users.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachUserSessionUser0(ctx, exec, 1, userSession0, user1)
	if err != nil {
		return err
	}

	userSession0.R.User = user1

	user1.R.UserSessions = append(user1.R.UserSessions, userSession0)

	return nil
}

func (userSession0 *UserSession) AttachUser(ctx context.Context, exec bob.Executor, user1 *User) error {
	var err error

	_, err = attachUserSessionUser0(ctx, exec, 1, userSession0, user1)
	if err != nil {
		return err
	}

	userSession0.R.User = user1

	user1.R.UserSessions = append(user1.R.UserSessions, userSession0)

	return nil
}
