# For more details, read this: https://coolify.io/docs/github-actions
name: Build Static Image
on:
  push:
    branches: ["develop"]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: ">=1.24.1"

      # - name: Run Migrations
      #   run: go run . migrate up

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}
      - name: Build image and push to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # - name: Dokploy Deployment
      #   shell: bash
      #   with:
      #     auth_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
      #     application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
      #     dokploy_url: ${{ secrets.DOKPLOY_URL }}
      - name: Trigger Dokploy deployment
        shell: bash
        env:
          DOKPLOY_URL: ${{ secrets.DOKPLOY_URL }}
          DOKPLOY_AUTH_TOKEN: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          DOKPLOY_APPLICATION_ID: ${{ secrets.DOKPLOY_APPLICATION_ID }}
        run: |
          response=$(curl -X 'POST' \
            "$DOKPLOY_URL/api/application.deploy" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "x-api-key: $DOKPLOY_AUTH_TOKEN" \
            -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
            -w "%{http_code}" \
            -o /dev/null \
            -s)

          if [ "$response" -ne 200 ]; then
            echo "Deployment failed with status code: $response"
            exit 1
          fi
