name: Build and test
on:
  push:
    branches: ["develop"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: tkahng/postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: authgo_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: true
          cache-dependency-path: go.sum
          go-version: "1.24.5" # Use Go version 1.23.5

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      - name: Setup Test DB
        run: go run . migrate testup

      - name: Run tests
        run: go test -v ./... -race -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Build image and push to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  migrate:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: true
          cache-dependency-path: go.sum
          go-version: "1.24.5" #

      - name: Run Migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: go run . migrate up

  deploy:
    needs: migrate
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dokploy deployment
        shell: bash
        env:
          DOKPLOY_URL: ${{ secrets.DOKPLOY_HOST }}
          DOKPLOY_AUTH_TOKEN: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          DOKPLOY_APPLICATION_ID: ${{ secrets.DOKPLOY_APPLICATION_ID }}
        run: |
          response=$(curl -X 'POST' \
            "$DOKPLOY_URL/api/application.deploy" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "Authorization: Bearer $DOKPLOY_AUTH_TOKEN" \
            -d "{\"applicationId\": \"$DOKPLOY_APPLICATION_ID\"}" \
            -w "%{http_code}" \
            -o /dev/null \
            -s)

          if [ "$response" -ne 200 ]; then
            echo "Deployment failed with status code: $response"
            exit 1
          fi
